name: CI

on:
  push:
    branches:
      - master
      - 'feature/**'
      - 'v**'
  pull_request:
    branches:
      - master
      - 'feature/**'
      - 'v**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install wabt
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v2
      with:
        go-version: '1.18.x'
    - uses: actions/setup-node@v2
      with:
        node-version: '15'
    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Test
      run: make
    - name: Check tidy
      run: make check-tidy

  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v2
      with:
        go-version: '1.18.1'
    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Check license headers
      run: make check-headers